name: B2500PKG_Proxy
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
version: "1.0"
slug: b2500pkg_proxy
description: MQTT-Proxy für Geräte mit gleicher Client-ID
options:
  devices:
    - port: 1901
      username: "user1"
      password: "pass1"
    - port: 1902
      username: "user2"
      password: "pass2"
    - port: 1903
      username: "user3"
      password: "pass3"

